version: "3.5"

services:

  couchdb:
    container_name: evt-drv-couchdb
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_APP_USER=${COUCHDB_APP_USER}
      - COUCHDB_APP_PASSWORD=${COUCHDB_APP_PASSWORD}
    build:
      context: .
      dockerfile: ${PWD}/dockerfiles/CouchDBDockerfile
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5984/']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5984:5984"
    networks:
      - evt-drv-net

  rabbitmq:
    container_name: evt-drv-rabbitmq
    image: rabbitmq:3.12-management
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'check_running']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - evt-drv-net

  app:
    container_name: evt-drv-app
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        # condition: service_healthy
        condition: service_healthy
    links:
      - rabbitmq
      - couchdb
    build:
      dockerfile: ${PWD}/dockerfiles/AppDockerfile
      context: ${PWD}/src
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_APP_USER=${COUCHDB_APP_USER}
      - COUCHDB_APP_PASSWORD=${COUCHDB_APP_PASSWORD}
      - ACCESS_TOKEN_SECRET_KEY=${ACCESS_TOKEN_SECRET_KEY}
    ports:
      - "1984:1984"
      - "80:80"
    volumes:
      - ${PWD}/src:/deploy
    networks:
      - evt-drv-net

networks:
  evt-drv-net:
    driver: bridge
