version: "3.5"

services:

  couchdb:
    container_name: evt-drv-couchdb
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_APP_USER=${COUCHDB_APP_USER}
      - COUCHDB_APP_PASSWORD=${COUCHDB_APP_PASSWORD}
    build:
      context: .
      dockerfile: ${PWD}/dockerfiles/CouchDBDockerfile
    ports:
      - "5984:5984"
    networks:
      - evt-drv-net

  rabbitmq:
    container_name: evt-drv-rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - evt-drv-net

  app:
    container_name: evt-drv-app
    depends_on:
      - rabbitmq
      - couchdb
    links:
      - rabbitmq
      - couchdb
    build:
      dockerfile: ${PWD}/dockerfiles/AppDockerfile
      context: ${PWD}/src
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_APP_USER=${COUCHDB_APP_USER}
      - COUCHDB_APP_PASSWORD=${COUCHDB_APP_PASSWORD}
    command: ["/bin/sh"]
    stdin_open: true
    tty: true
    ports:
      - "1984:1984"
    volumes:
      - ${PWD}/src:/deploy
    networks:
      - evt-drv-net

networks:
  evt-drv-net:
    driver: bridge
