#! /bin/bash

export COUCH_AUTH=$(echo -n $COUCHDB_USER:$COUCHDB_PASSWORD | base64)

curl -X POST -H "Authorization: Basic $COUCH_AUTH" -H "Content-Type: application/json" http://127.0.0.1:5984/_cluster_setup -d '{"action": "enable_single_node", "bind_address": "0.0.0.0"}'

echo -ne '{"name": "'"$COUCHDB_APP_USER"'", "password": "'"$COUCHDB_APP_PASSWORD"'", "roles": ["app"], "type": "user"}' | curl -X PUT -H "Authorization: Basic $COUCH_AUTH" "http://127.0.0.1:5984/_users/org.couchdb.user:$COUCHDB_APP_USER" -d @-
