# ==================================================================================================
#  Python project configuration
# ==================================================================================================

[tool.pytest.ini_options]
pythonpath = [
  "."
]
filterwarnings = [
  "ignore::DeprecationWarning"
]

[tool.pyright]
reportGeneralTypeIssues = "none"

[[tool.mypy.overrides]]
module = [
    "config.*",
    "core.*",
    "main.*",
    "database.*",
    "schemas.*",
    "pubsub.*",
    "services.*",
    "utils.*",
    "exceptions.*",
    "tests.*",
]
ignore_missing_imports = true
